version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: bank_postgres
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: bank_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: ${JWT_SECRET:-mySuperSecretKeyForJWTGenerationWithEnoughLengthForHS512!!!}
    ports:
      - "8080:8080"
    networks:
      - bank_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  bank_network:
    driver: bridge
