spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/bank_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/migration/master.yaml

encryption:
  secret-key: ${ENCRYPTION_SECRET:MySuperSecretKey12}

jwt:
  secret: ${JWT_SECRET:-mySuperSecretKeyForJWTGenerationWithEnoughLengthForHS512AndEvenMoreToBeSafe!!!}
  expiration: 86400000

server:
  port: 8080

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    liquibase: INFO
    com.example.bankcards.util: DEBUG